# Group Publisher Transaction Queries

## Publisher Transaction Queries

### List all TQs [GET]

### Create a TQ [POST]

### Delete a TQ [POST]

# Group Advertiser Transaction Queries

## Advertiser Transaction Queries

### List all TQs [GET]

### Approve a TQ [POST]

### Reject a TQ [POST]

### Pend a TQ [POST]

### Batch process TQs [POST]

## Transaction Query Reasons

### List all TQ reasons [GET]

### Create a TQ reason [POST]

### Delete a TQ reason [POST]
